### ISSUE TITLE
Document Custom Fields config syntax

### ISSUE THREAD

**Issue by kgoggin** [reasonml-community/graphql-ppx#194]
Hello! First off, just wanted to say that I've been following the GraphQL/ReasonML ecosystem for over two years now and I'm _so excited_ to see the progress being made on this PPX! This is seriously excellent work! 🎉

I've got a custom Date scalar in my schema that I use for fields as well as in inputs, but I think I'm missing something about how to set it in my bsconfig.json. Here's what I've got:

```json
"graphql": {
    "extend-query": "ReactQuery.ExtendQuery",
    "extend-mutation": "ReactQuery.ExtendMutation",
    "customFields": {
      "Date": "Date"
    }
  }
```
`Date` is the name of a module that defines `type t`, as well as `serialize` and `parse` functions.

I'd be great if the docs spelled out the format a little more clearly. Thanks!

**Comment by jfrolich** [comment]
We changed the preferred configuration form from `kebab-case` to `camelCase` in the configuration, but I missed `customFields`. I just pushed a new commit (871fef36638d2175839c1478584ba71d11b7b3ed) fixing this. Can you try? On your current release using `custom-fields` should work.

**Comment by jfrolich** [comment]
The documentation is in the `documentation` directory of this repo so if you have ideas on how to improve the documentation here I would certainly accept PR's!

**Comment by kgoggin** [comment]
Thanks for the quick reply! I tried installing that commit but then I get an error - `Fatal error: exception Failure("@reasonml-community/graphql-ppx/ppx not found when resolving ppx-flags")`.

I also tried changing to kebab-case on my initial setup but it still doesn't seem to be working. I've got an input type defined in my schema as:

```graphql
scalar Date

input UpsertStudentInput {
    id: ID
    firstName: String!
    lastName: String!
    color: APP_COLOR!
    slug: String!
    birthdate: Date!
    grade: GRADE!
  }
```

Then, I've got a mutation defined as:

**Comment by jfrolich** [comment]
Can you try if it works with the inline directive `@ppxCustom(module: Date)`?

**Comment by kgoggin** [comment]
I'm happy to, but can you help me understand where it belongs for an input argument? Does it go after the variable definition at the top of the operation or where it gets used at the field level?

**Comment by jfrolich** [comment]
Ah maybe the custom fields don't work for input args. Let me check later!

**Comment by jaredramirez** [comment]
I'm running into this too:
1. I can't figure out where to put the `@ppxCustom` for input arguments
2. I have a very similar setup to kgoggin (defining `customFields` in `bsconfig.json`), and the ppx isn't automatically decoding the scalars. This is happening even for non-input fields. However, using  `@ppxCustom` (again for non-input fields) with the same modules I define in `bsconfig.json` works as expected

**Comment by russellmcc** [comment]
Is it possible to use custom scalars for input arguments?  I'm confused about how to do this.

**Comment by jfrolich** [comment]
No but that would certainly be cool, PR would be welcome, and otherwise this is something I want to be looking at, at some point.
